# NumPy Exercises for Data Analysis

*by Selva Prabhakaran*

From the website: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

1. (L1) numpy를 `np`로 임포트 및 버전 확인
2. (L1) 0-9값을 가지는 1D array 생성
3. (L1) 1차원 array를 2차원으로 변경
4. (L2) 두 Array를 수직, 수평으로 합치기
5. (L2) a array를 3번 반복한 값과 각 값을 3번씩 반복하여 값을 하나로 합치시오
- 결과: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
6. (L2) a array에서 5~10사이의 값만 출력
7. (L2) Base function을 참고하여 두 벡터를 비교하여 더 큰 값만 만드는 함수를 구성하고 출력하시오
- 결과: [6 7 9 8 9 7 5]
8. (L2) 2차원 array에서 행/열의 순서를 역으로 변환하시오
9. (L2) iris dataset 임포트 및 데이터 확인 ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
10. (L2) 종(species)에 대하여 1차원 데이터로 추출하기
11. (L2) 2차원 형태의 Iris 데이터로 불러오기 ('종(species)' 정보는 생략한다)
12. (L1) sepal length (1번째 열) 정보에 대하여 평균, 중앙값, 분산을 구한다.
13. (L2) sepal length (1번째 열) 정보에 대하여 0~1 사이의 값으로 정규화한다. (min-max scaling)
14. (L3) sepal llength (1번째 열) 정보에 대하여 Softmax 점수를 구한다.
15. (L1) iris_2d 데이터에 랜덤으로 20개의 nan 값을 삽입한다.
16. (L2) iris_2d 데이터의 sepal llength (1번째 열)에 대하여 nan 값을 발견한다.
17. (L2) nan값을 0으로 치환한다.
18. (L2) petal length (3번째 열)에 대하여 다음의 규칙을 적용한다.
* Less than 3 --> 'small'
* 3-5 --> 'medium'
* '>=5 --> 'large'
19. (L3) Setose를 Versicolor와 Verginica보다 2배의 확률로 더 많이 뽑도록 램덤 샘플링한다.
20. (L2) sepal length 열을 기준으로 iris 데이터를 정렬한다.
21. (L2) 배열 a로 부터 30이상 값은 30으로, 10 이하의 값은 10으로 치환한다.
22. (L2) 배열 a로 부터 가장 큰 5개의 값만 반환한다.
23. (L2) 배열들의 배열을 사용하여 1차원 배열을 생성하시오.
Desired output:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
24. (L2) 각 행에서 가장 큰 값들만 반환한다.
25. (L3) 이미지를 numpy array로 변환한다.
26. (L2) 1차원 numpy array에서 nan 값들을 없앤다.
27. (L3) 두 벡터 사이의 Euclidean 거리를 계산한다.
28. (L3) 1차원 배열에서 3개씩 확인하여 평균값을 매긴 배열을 생성한다.

#### 1. (L1) numpy를 `np`로 임포트 및 버전 확인

In [2]:
import numpy as np
print(np.version.version)

1.26.4


#### 2. (L1) 0-9값을 가지는 1D array 생성

In [3]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. (L1) 1차원 array를 2차원으로 변경

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reshaped_arr = arr.reshape((2, 5))
print(reshaped_arr)

# -1 sets the dimension automatically
reshaped_arr = arr.reshape((2, -1))
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 4. (L2) 두 Array를 수직, 수평으로 합치기

In [5]:
# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a, b)

c = np.vstack([a, b])
print(c)

d = np.hstack([a, b])
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### 5. (L2) a array를 3번 반복한 값과 각 값을 3번씩 반복하여 값을 하나로 합치시오
- 결과: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]

In [6]:
# Input
a = np.array([1,2,3])

# This repeats EACH ELEMENT along given axis
b = a.repeat(3)

# This repeats WHOLE ARRAY, as tiles
triple_a = np.tile(a, 3)

c = np.hstack([b, triple_a])
print(c)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


#### 6. (L2) a array에서 5~10사이의 값만 출력

In [7]:
# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Middle ground
b = a[np.where((a <= 10) & (a >= 5))]
print(b)

# Shorthand
c = a[(a >= 5) & (a <= 10)]
print(c)

# Extended
d = a[np.where(np.logical_and(a >=5, a <= 10))]
print(d)

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


#### 7. (L2) Base function을 참고하여 두 벡터를 비교하여 더 큰 값만 만드는 함수를 구성하고 출력하시오

In [9]:
# Base function
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Inputs
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Direct definition
def pair_max(input_a, input_b):
    return np.where(input_a > input_b, input_a, input_b)

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


#### 8. (L2) 2차원 array에서 행/열의 순서를 역으로 변환하시오

In [14]:
arr = np.arange(9).reshape(3,3)
print(arr)

# 행 순서 변경
reversed_rows = np.flip(arr, axis=0)
print(reversed_rows)

# 열 순서 변경
reversed_cols = np.flip(arr, axis=1)
print(reversed_cols)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


#### 9. (L2) iris dataset 임포트 및 데이터 확인

In [17]:
IRIS_DATASET_URL = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# None or object returns an ARRAY of ROWS (as tuples)
# since dtypes are not uniform and defined across all columns
iris_dataset = np.genfromtxt(IRIS_DATASET_URL, delimiter=',', dtype=object)
print(iris_dataset)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

#### 10. (L2) 종(species)에 대하여 1차원 데이터로 추출하기

In [18]:
COLUMN_NAMES = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = [
    row[4] for row in iris_dataset
]
print(species)

[b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',

#### 11. (L2) 2차원 형태의 Iris 데이터로 불러오기 ('종(species)' 정보는 생략한다)

In [21]:
# Removing string column makes all columns of uniform type, so it can be inferred
# and NumPy sees that it must be a matrix of floats
iris_2d = np.genfromtxt(IRIS_DATASET_URL, delimiter=',', dtype=None, usecols=[0,1,2,3])

print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


#### 12. (L1) sepallength (1번째 열) 정보에 대하여 평균, 중앙값, 분산을 구한다.

In [25]:
print(f"평균: {np.mean(iris_2d[:,0])}")
print(f"중앙: {np.median(iris_2d[:,0])}")
print(f"분산: {np.std(iris_2d[:,0])}")

평균: 5.843333333333334
중앙: 5.8
분산: 0.8253012917851409


#### 13. (L2) sepallength (1번째 열) 정보에 대하여 0~1 사이의 값으로 정규화한다. (min-max scaling)

In [26]:
sepallength = iris_2d[:,0]

maximum_sepallength = np.max(sepallength)
minimum_sepallength = np.min(sepallength)

normalized_sepallength = (sepallength.copy() - minimum_sepallength) / (maximum_sepallength - minimum_sepallength)
print(normalized_sepallength)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

#### 14. (L3) sepalllength (1번째 열) 정보에 대하여 Softmax 점수를 구한다.

In [27]:
# https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python
softmax_exponentials = np.exp(sepallength - np.max(sepallength))
softmax = softmax_exponentials / softmax_exponentials.sum(axis=0)

with np.printoptions(precision=3):
    print(softmax)

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


#### 15. (L1) iris_2d 데이터에 랜덤으로 20개의 nan 값을 삽입한다.

In [29]:
iris_with_random_nans = iris_2d.copy()
iris_with_random_nans[
    np.random.choice(iris_with_random_nans.shape[0] - 1, size=20),
    np.random.choice(iris_with_random_nans.shape[1] - 1, size=20)
] = np.nan
print(iris_with_random_nans[:5])

[[nan 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


#### 16. (L2) iris_2d 데이터의 sepalllength (1번째 열)에 대하여 nan 값을 발견한다.

In [30]:
nan_indices = np.argwhere(
    np.isnan(iris_with_random_nans)
)
print(nan_indices, nan_indices.shape[0])

[[  0   0]
 [ 13   1]
 [ 13   2]
 [ 17   0]
 [ 17   2]
 [ 30   2]
 [ 43   1]
 [ 53   2]
 [ 68   0]
 [ 70   2]
 [ 72   1]
 [ 78   1]
 [ 91   2]
 [105   2]
 [106   2]
 [131   2]
 [138   0]] 17


#### 17. (L2) nan값을 0으로 치환한다.

In [36]:
# Input
nanified_iris_2d = iris_2d.copy()
nanified_iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

nanified_iris_2d[np.isnan(nanified_iris_2d)] = 0

print(nanified_iris_2d[:5])
print("-" * 50)
print(np.isnan(nanified_iris_2d).any())

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
--------------------------------------------------
False


#### 18. (L2) petal length (3번째 열)에 대하여 다음의 규칙을 적용한다.
* Less than 3 --> 'small'
* 3-5 --> 'medium'
* '>=5 --> 'large'

In [39]:
petallength = iris_2d[:, 2]

bins = [0.0, 3.0, 5.0]
bins_labels = ['small', 'medium', 'large']
petallength_put_in_bins = np.digitize(petallength, bins)
petallength_categories = [
    bins_labels[bin_number-1]
    for bin_number in petallength_put_in_bins
]
print(petallength_categories)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

#### 19. (L3) Setose를 Versicolor와 Verginica보다 2배의 확률로 더 많이 뽑도록 램덤 샘플링한다.

In [ ]:
probabilities_map = {
    b'Iris-setosa': 0.5,
    b'Iris-versicolor': 0.25,
    b'Iris-virginica': 0.25
}
sampling_probabilities = np.array([
    probabilities_map.get(name)
    for name in species
])
sampling_distribution = sampling_probabilities / sum(sampling_probabilities)
sample = np.random.choice(species, size=100, p=sampling_distribution)
np.unique(sample, return_counts=True)

#### 20. (L2) sepal length 열을 기준으로 iris 데이터를 정렬한다.

In [ ]:
sorted_sepallength_indices = iris_2d[:,0].argsort()
sorted_iris_array = iris_dataset[sorted_sepallength_indices]
print(sorted_iris_array)

#### 21. (L2) 배열 a로 부터 30이상 값은 30으로, 10 이하의 값은 10으로 치환한다.

In [41]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a > 30] = 30
a[a < 10] = 10
print(a)

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


#### 22. (L2) 배열 a로 부터 가장 큰 5개의 값만 반환한다.

In [42]:
# Inputs

np.random.seed(100)
a = np.random.uniform(1,50, 20)

np.argsort(a)[:5]

array([ 4, 13,  5,  8, 17])

#### 23. (L2) 배열들의 배열을 사용하여 1차원 배열을 생성하시오.

Desired output:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [43]:
# Inputs

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

np.hstack([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 24. (L2) 각 행에서 가장 큰 값들만 반환한다.

In [47]:
# Input

np.random.seed(100)
a = np.random.randint(1,10, [5,3])

print([
    np.max(row)
    for row in a
])

np.amax(a, axis=1)

[9, 8, 6, 3, 9]


array([9, 8, 6, 3, 9])

#### 25. (L3) 이미지를 numpy array로 변환한다.

In [48]:
from PIL import Image
import requests
import io

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

downloaded_image = Image.open(
    io.BytesIO(
        requests.get(URL).content
    )
)
np.array(
    list(
        downloaded_image.getdata()
    )
)

/Users/macbook-0042/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


array([[  9,  72, 125],
       [  9,  72, 125],
       [  9,  72, 125],
       ...,
       [ 15,  51,  77],
       [ 12,  48,  74],
       [ 11,  45,  72]])

#### 26. (L2) 1차원 numpy array에서 nan 값들을 없앤다.

In [49]:
# Input

a = np.array([1,2,3,np.nan,5,6,7,np.nan])

a = a[
    np.where(
        np.isnan(a) == False
    )
]
print(a)

[1. 2. 3. 5. 6. 7.]


#### 27. (L3) 두 벡터 사이의 Euclidean 거리를 계산한다.

In [50]:
# Inputs

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

manual = np.sqrt(
    np.sum((b - a)**2)
)

linalg = np.linalg.norm(a-b)
print(manual == linalg)

True


#### 28. (L3) 1차원 배열에서 3개씩 확인하여 평균값을 매긴 배열을 생성한다.

In [60]:
# Inputs

np.random.seed(100)
Z = np.random.randint(10, size=10)

window_size = 3

convoluted = [np.average(Z[index:index+window_size]) for index in range(0, Z.shape[0]-window_size+1)]

print(Z)
print(convoluted)

[8 8 3 7 7 0 4 2 5 2]
[6.333333333333333, 6.0, 5.666666666666667, 4.666666666666667, 3.6666666666666665, 2.0, 3.6666666666666665, 3.0]
