## Numpy Problems 
- [넘파이 핵심 내용](https://assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)을 참고하여 다음을 응답하시오

In [1]:
import numpy as np
import unittest

In [11]:
class TestArray(unittest.TestCase):

    def test_number_1(self):
        for _ in range(10):
            random_number_list = list(np.random.randint(1e2, size=10))
            pred = total_exercise_time(random_number_list)
            self.assertEqual(pred, np.sum(random_number_list))

    def test_number_2(self):
        for _ in range(10):
            random_number_list = np.random.randint(1e2, size=(4,2))
            pred = total_distance(random_number_list)
            check = np.sqrt(np.sum(np.diff(random_number_list, axis=0)**2, axis=1))
            self.assertEqual(pred, np.round(np.sum(check), 2))

    def test_number_3(self):
        for _ in range(10):
            transactions = ["in" if n >=5 else "out" for n in np.random.randint(10, size=10)]
            amounts = [n for n in np.random.randint(100, size=10)]
            pred = final_inventory(transactions, amounts)
            self.assertEqual(pred, np.sum(np.where(transactions=='in', 1, -1) * amounts))
    
    def test_number_4(self):
        angle_list = [90, 180, 270, 30]
        for angle in angle_list:
            arr = np.random.randint(4, size=(3,3))
            pred = rotate_array(arr, angle)
            if angle == 90:
                self.assertEqual(pred.tolist(), np.transpose(arr[::-1]).tolist())
            elif angle == 180:
                self.assertEqual(pred.tolist(), arr[::-1, ::-1].tolist())
            elif angle == 270:
                self.assertEqual(pred.tolist(), np.transpose(arr)[::-1].tolist())
            else:
                self.assertEqual(pred, '오류')
    
    def test_number_5(self):
        for _ in range(10):
            message_matrix = np.random.randint(10, size=(2,2))
            key_matrices = [np.random.randint(10, size=(2,2)), np.random.randint(10, size=(2,2))]
            pred = decrypt_message_multi_step(message_matrix, key_matrices)
            for key in key_matrices:
                message_matrix = np.dot(message_matrix, key)
            self.assertEqual(pred.tolist(), message_matrix.tolist())

    def test_number_6(self):
        for _ in range(10):
            a = np.random.randint(100, size=(3,3))
            b = np.random.randint(1, size=(3,3))
            c = np.random.randint(1, size=3)
            pred = weather_prediction(a,b,c)
            self.assertEqual(pred.tolist(), np.dot(np.dot(a,b), c).tolist())

### 난이도 1: 미션 - 우주 비행사 훈련

**배경 이야기:**
- 우주 비행사가 되기 위해서는 강력한 체력과 지구력 훈련이 필요합니다. 그 중 중요한 훈련 중 하나는 일정 시간 동안 다양한 운동을 반복하는 것입니다. 우주 비행사들은 매일 다양한 운동을 수행해야 하며, 각 운동에 할당된 시간이 다릅니다. 당신은 우주 비행사 훈련 프로그램의 일일 운동 시간을 계산하는 임무를 맡았습니다.

**문제 설명:**
- 우주 비행사들이 매일 수행해야 하는 운동 시간 목록이 있습니다. 이 목록은 numpy 배열로 주어지며, 배열의 각 요소는 특정 운동을 수행하는 데 걸리는 시간을 분 단위로 나타냅니다. 당신의 임무는 이 배열을 받아서 총 운동 시간을 계산하는 것입니다.

**입력:**
- 하나의 numpy 배열 exercise_times가 주어집니다. 이 배열은 우주 비행사들이 수행해야 하는 각 운동의 시간을 분 단위로 나타냅니다.

**출력:**
- 우주 비행사들이 하루에 운동하는 총 시간을 분 단위로 출력하세요.

**예시:**
```
exercise_times = np.array([30, 45, 20, 10, 60])  # 각 운동의 시간 (분)

# 기대 출력:
165
```

In [3]:
def total_exercise_time(exercise_times):
    # TODO: 문제를 해결하시오
    return np.sum(exercise_times)

In [4]:
# 테스트 연습
exercise_times = np.array([30, 45, 20, 10, 60])
print(total_exercise_time(exercise_times))  # 165 출력

165


In [5]:
# 최종 테스트
tbm = TestArray()
tbm.test_number_1()
print("완벽합니다~!")

완벽합니다~!


### 난이도 2: 미션 - 우주 탐사 로봇의 이동 경로 계산

**배경 이야기:**
- 우주 탐사 로봇은 화성 표면을 탐사하며 여러 지점을 방문합니다. 로봇은 특정한 지점을 방문할 때마다 자신의 위치를 기록합니다. 당신의 임무는 로봇이 이동한 경로의 총 거리를 계산하는 것입니다.

**문제 설명:**
- 로봇의 이동 경로는 여러 지점의 좌표로 주어집니다. 각 지점은 2차원 평면의 좌표 (x, y)로 나타납니다. numpy 배열로 주어진 이 좌표들을 이용해 로봇이 이동한 총 거리를 계산하세요.

**입력:**
- 2차원 numpy 배열 coordinates가 주어집니다. 이 배열의 각 행은 로봇이 방문한 지점의 (x, y) 좌표를 나타냅니다.

**출력:**
- 로봇이 이동한 총 거리를 소수점 세번째 자리에서 반올림하시오.

**예시:**
```
coordinates = np.array([
    [0, 0],
    [3, 4],
    [6, 8],
    [9, 12]
])  # 각 지점의 좌표

# 기대 출력:
15.00
```

In [12]:
def total_distance(coordinates: np.array):
    # 두 점 사이의 거리 계산
    diff = np.diff(coordinates, axis=0)
    distances = np.sqrt(np.sum(diff**2, axis=1))
    return np.round(np.sum(distances), 2)

In [13]:
# 테스트 연습
coordinates = np.array([
    [0, 0],
    [3, 4],
    [6, 8],
    [9, 12]
])
print(f"{total_distance(coordinates):.2f}")  # 15.00 출력

15.00


In [14]:
# 테스트
tbm = TestArray()
tbm.test_number_2()
print("완벽합니다~!")

완벽합니다~!


In [ ]:
민우님 강의 요청
AI 요청 강의 관심



### 난이도 2: 미션 - 물류 창고의 재고 관리

**배경 이야기:**
- 대형 물류 창고에서는 다양한 제품이 입고되고 출고됩니다. 각 제품의 입고와 출고 기록을 분석하여 특정 시점에서의 재고 수량을 계산해야 합니다. 당신의 임무는 각 제품의 일일 재고 변동을 기반으로 최종 재고를 계산하는 것입니다.

**문제 설명:**
- 하루 동안의 제품 입고와 출고 기록이 numpy 배열로 주어집니다. 각 기록은 '입고' 또는 '출고'로 구분되며, 그에 따라 재고가 증가하거나 감소합니다. 이 데이터를 이용해 하루가 끝날 때의 최종 재고를 계산하세요.

**입력:**
- 두 개의 numpy 배열 transactions와 amounts가 주어집니다.
- transactions: 'in' 또는 'out'으로 구성된 문자열 배열로, 각 요소는 해당 시간에 발생한 입고 또는 출고를 나타냅니다.
- amounts: 각 입고 또는 출고 시의 수량을 나타내는 정수 배열입니다.

**출력:**
- 하루가 끝날 때의 최종 재고 수량을 정수로 출력하세요.

**예시:**
```
transactions = np.array(['in', 'out', 'in', 'in', 'out'])
amounts = np.array([100, 50, 200, 150, 100])  # 각 거래의 수량

# 기대 출력
300
```


In [15]:
def final_inventory(transactions, amounts):
    # 'in'은 1, 'out'은 -1로 매핑
    transaction_map = np.where(transactions == 'in', 1, -1)
    # 각 거래의 영향을 계산
    total_amounts = transaction_map * amounts
    # 최종 재고 계산
    return np.sum(total_amounts)

In [16]:
# 테스트 연습
transactions = np.array(['in', 'out', 'in', 'in', 'out'])
amounts = np.array([100, 50, 200, 150, 100])
print(final_inventory(transactions, amounts))  # 300 출력

300


In [17]:
# 테스트
tbm = TestArray()
tbm.test_number_3()
print("완벽합니다~!")

완벽합니다~!


### 난이도 2: 미션 - 사진 편집기

**배경 이야기:**

- 당신은 인기 있는 사진 편집기 앱의 개발자입니다. 사용자들은 앱을 사용하여 사진을 다양한 각도로 회전할 수 있어야 합니다. 이 기능을 구현하기 위해 2차원 배열로 표현된 이미지를 주어진 각도만큼 회전시키는 함수를 작성해야 합니다. 각도는 90도, 180도, 270도 중 하나만 가능합니다.

**문제 설명:**

- 2차원 numpy 배열로 주어진 이미지를 주어진 각도만큼 회전시키세요. 각도는 90도, 180도, 270도 중 하나입니다. 주어진 각도만큼 회전된 새로운 배열을 반환하는 함수를 작성하세요.

**입력:**

- arr: 2차원 numpy 배열. 회전시킬 이미지.
- angle: 정수. 회전 각도 (90, 180, 270도 중 하나).

**출력:**

- 주어진 각도만큼 회전된 새로운 2차원 numpy 배열을 반환하세요.

**제약 조건:**
- 입력 각도는 90, 180, 270도 중 하나입니다. 다른 각도를 입력했을 때 '오류'를 반환하시오.

**예시:**
```
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
angle = 90

# 기대 출력
array([
    [7, 4, 1],
    [8, 5, 2],
    [9, 6, 3]
])
```

In [51]:
def rotate_array(arr: np.ndarray, angle: int) -> np.ndarray:
    """주어진 2차원 배열을 주어진 각도만큼 회전시킨 새로운 배열을 반환합니다."""
    if angle == 90:
        return np.transpose(arr[::-1])
    elif angle == 180:
        return arr[::-1, ::-1]
    elif angle == 270:
        return np.transpose(arr)[::-1]
    else:
        return '오류'

In [52]:
# 테스트
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
angle = 90
print(rotate_array(arr, angle))

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [66]:
# 테스트
tbm = TestArray()
tbm.test_number_4()
print("완벽합니다~!")

완벽합니다~!


### 난이도 3: 미션 - 스파이 메시지 암호 해독: 다중 단계 행렬 연산

**배경 이야기:**
- 당신은 비밀 정보 기관의 암호 해독 전문가입니다. 적국의 스파이들은 매우 복잡한 암호화 방식을 사용하고 있습니다. 암호화된 메시지는 여러 단계의 행렬 연산을 통해 생성되며, 각 단계는 특정한 키 행렬을 사용합니다. 당신의 임무는 이 다중 단계 행렬 연산을 해독하여 최종 메시지를 복원하는 것입니다.

**문제 설명:**
- 암호화된 메시지를 해독하기 위해 주어진 여러 키 행렬을 순차적으로 사용하여 행렬 곱셈을 수행해야 합니다. 주어진 초기 메시지 행렬과 여러 키 행렬들을 차례로 곱하여 최종 메시지를 복원하세요.

**입력:**
- message_matrix: 2차원 numpy 배열. 초기 암호화된 메시지를 나타내는 행렬.
- key_matrices: 3차원 numpy 배열. 각 2차원 배열이 행렬 곱셈에 사용될 키 행렬을 나타냅니다.

**출력:**
- 모든 키 행렬을 순차적으로 곱한 최종 해독된 메시지를 나타내는 2차원 numpy 배열을 반환하세요.

**제약 조건:**
- message_matrix와 key_matrices의 크기는 행렬 곱셈이 가능하도록 주어집니다. 즉, 각 단계의 행렬 곱셈이 유효하게 수행될 수 있습니다.

**예시:**
```
import numpy as np

message_matrix = np.array([
    [1, 2],
    [3, 4]
])

key_matrices = np.array([
    [[2, 0],
     [1, 2]],
    
    [[1, 1],
     [0, 1]]
])
```

In [69]:
def decrypt_message_multi_step(message_matrix: np.ndarray, key_matrices: np.ndarray) -> np.ndarray:
    """
    주어진 초기 메시지 행렬과 여러 키 행렬을 순차적으로 곱하여 최종 해독된 메시지를 반환합니다.
    
    매개변수:
    message_matrix (np.ndarray): 초기 암호화된 메시지를 나타내는 행렬
    key_matrices (np.ndarray): 각 2차원 배열이 행렬 곱셈에 사용될 키 행렬을 나타내는 3차원 배열
    
    반환값:
    np.ndarray: 최종 해독된 메시지를 나타내는 행렬
    """
    result = message_matrix
    for key_matrix in key_matrices:
        result = np.dot(result, key_matrix)
    return result

In [70]:
# 테스트
message_matrix = np.array([
    [1, 2],
    [3, 4]
])

key_matrices = np.array([
    [[2, 0],
     [1, 2]],
    
    [[1, 1],
     [0, 1]]
])

print(decrypt_message_multi_step(message_matrix, key_matrices))

[[ 4  8]
 [10 18]]


In [82]:
# 테스트
tbm = TestArray()
tbm.test_number_5()
print("완벽합니다~!")

완벽합니다~!


### 난이도 4: 미션 - 날씨 예측 모델


**배경 이야기:**
- 당신은 기상 예측 기관에서 일하는 데이터 과학자입니다. 다양한 날씨 데이터를 바탕으로 향후 날씨를 예측하는 모델을 개발하고 있습니다. 이 모델은 여러 날의 온도, 습도, 기압 등의 데이터를 입력받아 이를 분석하여 향후 날씨를 예측합니다. 이를 위해 주어진 데이터에 대해 복잡한 수학적 연산을 수행해야 합니다.

**문제 설명:**
- 주어진 2차원 numpy 배열은 여러 날에 대한 다양한 기상 데이터 (예: 온도, 습도, 기압 등)를 포함하고 있습니다. 이 데이터를 바탕으로 특정 연산을 수행하여 향후 날씨를 예측하는 모델을 구현하세요. 예를 들어, 각 날의 데이터를 특정 행렬과 곱한 후, 그 결과를 이용하여 예측값을 도출해야 합니다.

**입력:**
- weather_data: 2차원 numpy 배열. 각 행은 특정 날의 기상 데이터를 나타냅니다.
- transformation_matrix: 2차원 numpy 배열. 기상 데이터를 변환하는 데 사용할 행렬입니다.
- weight_vector: 1차원 numpy 배열. 변환된 데이터를 가중합하여 최종 예측값을 계산하는 데 사용할 벡터입니다.

**출력:**
- 주어진 기상 데이터를 변환하고 가중합하여 도출된 예측값을 포함한 1차원 numpy 배열을 반환하세요.
- 이 때, 변환이란 행렬곱 연산을 의미합니다.

**제약 조건:**
- weather_data와 transformation_matrix의 크기는 행렬 곱셈이 가능하도록 주어집니다. 즉, weather_data의 열의 수는 transformation_matrix의 행의 수와 같습니다.
- transformation_matrix와 weight_vector의 크기도 연산이 가능하도록 주어집니다. 즉, transformation_matrix의 열의 수는 weight_vector의 길이와 같습니다.

**예시:**
```
weather_data = np.array([
    [20, 85, 1015],
    [25, 80, 1010],
    [30, 75, 1005]
])

transformation_matrix = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

weight_vector = np.array([0.3, 0.5, 0.2])

### 기대 출력
array([ 582.5,  725. ,  867.5])
```

In [83]:
import numpy as np

def weather_prediction(weather_data: np.ndarray, transformation_matrix: np.ndarray, weight_vector: np.ndarray) -> np.ndarray:
    """
    주어진 기상 데이터를 변환하고 가중합하여 도출된 예측값을 반환합니다.
    
    매개변수:
    weather_data (np.ndarray): 각 날의 기상 데이터를 나타내는 2차원 배열
    transformation_matrix (np.ndarray): 기상 데이터를 변환하는 데 사용할 행렬
    weight_vector (np.ndarray): 변환된 데이터를 가중합하여 최종 예측값을 계산하는 데 사용할 벡터
    
    반환값:
    np.ndarray: 예측값을 포함한 1차원 배열
    """
    # 기상 데이터를 변환 행렬과 곱함
    transformed_data = np.dot(weather_data, transformation_matrix)
    # 변환된 데이터를 가중합하여 예측값 계산
    predictions = np.dot(transformed_data, weight_vector)
    return predictions

In [84]:
# 테스트
weather_data = np.array([
    [20, 85, 1015],
    [25, 80, 1010],
    [30, 75, 1005]
])

transformation_matrix = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

weight_vector = np.array([0.3, 0.5, 0.2])

print(weather_prediction(weather_data, transformation_matrix, weight_vector))

[847.3  841.85 836.4 ]


In [86]:
# 테스트
tbm = TestArray()
tbm.test_number_6()
print("완벽합니다~!")

완벽합니다~!
